# Generated by Django 2.2.6 on 2021-05-27 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Derive',
            fields=[
                ('dev_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='设备id')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('dev_state', models.IntegerField(choices=[(0, '离线'), (1, '在线')], default=0, verbose_name='是否在线')),
                ('isDelete', models.IntegerField(choices=[(0, '有效'), (1, '无效')], default=0, verbose_name='是否有效')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='用户id')),
                ('user_pass', models.CharField(max_length=64, verbose_name='用户密码')),
                ('user_name', models.CharField(max_length=64, verbose_name='用户名')),
                ('user_email', models.EmailField(max_length=254, verbose_name='用户Email')),
                ('user_tel', models.CharField(max_length=64, null=True, verbose_name='用户Tel')),
                ('isDelete', models.IntegerField(choices=[(0, '有效'), (1, '无效')], default=0, verbose_name='是否有效')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NEQ', models.CharField(max_length=64, verbose_name='NEQ')),
                ('NER', models.CharField(max_length=64, verbose_name='NER')),
                ('SWQ', models.CharField(max_length=64, verbose_name='SWQ')),
                ('SWR', models.CharField(max_length=64, verbose_name='SWR')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('isDelete', models.IntegerField(choices=[(0, '有效'), (1, '无效')], default=0, verbose_name='是否有效')),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapwebapp.Derive', verbose_name='设备id')),
            ],
        ),
        migrations.AddField(
            model_name='derive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapwebapp.User', verbose_name='用户id'),
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False, verbose_name='数据id')),
                ('weideg', models.CharField(max_length=64, verbose_name='纬度')),
                ('jingdeg', models.CharField(max_length=64, verbose_name='经度')),
                ('wei', models.CharField(choices=[('S', '南纬'), ('N', '北纬'), ('0', '0')], default='N', max_length=16, verbose_name='纬度半球')),
                ('jing', models.CharField(choices=[('E', '东经'), ('W', '西经'), ('0', '0'), ('180', '180')], default='E', max_length=16, verbose_name='经度半球')),
                ('GPSdate', models.DateTimeField(verbose_name='GPS时间')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('isDelete', models.IntegerField(choices=[(0, '有效'), (1, '无效')], default=0, verbose_name='是否有效')),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapwebapp.Derive', verbose_name='设备id')),
            ],
            options={
                'verbose_name': '数据',
                'verbose_name_plural': '数据',
                'unique_together': {('dev', 'weideg', 'jing', 'GPSdate')},
            },
        ),
    ]
